spring:

  h2:
    console.enabled: true

  datasource:
    url: jdbc:h2:mem:droneDb
    username: drone
    password: drone
    driverClassName: org.h2.Driver

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
